name := "Checkers"
version := "0.1"
scalaVersion := "2.13.2"

libraryDependencies += "org.scalactic" %% "scalactic" % "3.1.2"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.1.2" % "test"
libraryDependencies += "org.scalatestplus" %% "junit-4-12" % "3.1.2.0" % "test"
//libraryDependencies += "org.scalafx" %% "scalafx" % "13.0.14-R19"
libraryDependencies += "org.scalafx" %% "scalafx" % "12.0.2-R18"
libraryDependencies += "org.openjfx" % "javafx" % "12.0.2"